name: C++ Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Intall dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++ make
    - name: Clean build directory
      run: rm -rf build

    - name: Create build repository
      run: mkdir build

    - name: Configure project with cmake
      run: cmake -S . -B build

    - name: Run tests
      run: | 
        cd build
        make
        ctest --output-on-failure
